import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";

import "@/_styles/_reset.scss";
import "@/_styles/_base.scss";
import { Header } from "./components/header/header";

const notoSansJP = Noto_Sans_JP({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "MealMind",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="ja" className={notoSansJP.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
